"""Engine lifecycle and QuickJS execution manager for Mirage."""

from __future__ import annotations

import json
import os
import threading
from typing import Any, Dict, List, Optional
import quickjs

from mirage.fonts import get_default_font_manager


_JS_DIR = os.path.join(os.path.dirname(__file__), "js")
_MICRO_DOM_PATH = os.path.join(_JS_DIR, "micro_dom.js")
_PLOTLY_BASIC_PATH = os.path.join(_JS_DIR, "plotly_basic.js")

_ENGINE_THREAD_LOCAL = threading.local()


class MirageEngine:
    """Manages an embedded QuickJS runtime with micro-DOM and Plotly.js."""

    def __init__(self) -> None:
        self.font_manager = get_default_font_manager()
        self.context = quickjs.Context()
        self.context.set_max_stack_size(10 * 1024 * 1024)

        # Register font measurement callback
        self.context.add_callable("_measureTextRaw", self.font_manager.measure_raw)

        # Load JavaScript assets
        with open(_MICRO_DOM_PATH, "r", encoding="utf-8") as f:
            micro_dom_js = f.read()

        with open(_PLOTLY_BASIC_PATH, "r", encoding="utf-8") as f:
            plotly_js = f.read()

        self.context.eval(micro_dom_js)
        self.context.eval(plotly_js)

        # Define render helper
        self.context.eval("""
        function mirageRender(dataJson, layoutJson) {
            var data = JSON.parse(dataJson);
            var layout = JSON.parse(layoutJson);

            var w = layout.width || 600;
            var h = layout.height || 400;

            var container = document.createElement('div');
            container.id = 'mirage-plot-' + Math.random().toString(36).slice(2);
            container.clientWidth = w;
            container.clientHeight = h;
            container.offsetWidth = w;
            container.offsetHeight = h;
            container.getBoundingClientRect = function() {
                return { left: 0, top: 0, right: w, bottom: h, width: w, height: h };
            };
            document.body.appendChild(container);

            try {
                Plotly.newPlot(container, data, layout, { staticPlot: true });
                var svgs = container.querySelectorAll('svg');
                if (svgs.length === 0) return null;
                var mainSvg = svgs[0];
                for (var s = 1; s < svgs.length; s++) {
                    var otherSvg = svgs[s];
                    var kids = otherSvg.childNodes.slice();
                    for (var k = 0; k < kids.length; k++) {
                        var kid = kids[k];
                        if (kid.nodeType === 1 && kid.classList && kid.classList.contains('hoverlayer')) continue;
                        mainSvg.appendChild(kid);
                    }
                }
                var res = mainSvg.outerHTML;
                document.body.removeChild(container);
                return res;
            } catch(e) {
                try { document.body.removeChild(container); } catch(ignore) {}
                throw new Error("Plotly render failed: " + e.message + "\\n" + e.stack);
            }
        }
        """)

    def render_svg(
        self,
        data: List[Dict[str, Any]],
        layout: Dict[str, Any],
        width: Optional[int] = None,
        height: Optional[int] = None,
    ) -> str:
        """Render Plotly traces and layout to a clean SVG XML string."""
        layout_copy = dict(layout) if layout else {}
        if width is not None:
            layout_copy["width"] = width
        if height is not None:
            layout_copy["height"] = height

        data_json = json.dumps(data)
        layout_json = json.dumps(layout_copy)

        # Call mirageRender inside QuickJS
        self.context.eval(f"var __mirage_data = {json.dumps(data_json)};")
        self.context.eval(f"var __mirage_layout = {json.dumps(layout_json)};")
        svg = self.context.eval("mirageRender(__mirage_data, __mirage_layout);")
        if not svg:
            raise RuntimeError("Mirage rendering failed: No SVG element was generated by Plotly.")
        return svg


def get_engine() -> MirageEngine:
    """Get or create the thread-local Mirage engine instance."""
    if not hasattr(_ENGINE_THREAD_LOCAL, "engine"):
        _ENGINE_THREAD_LOCAL.engine = MirageEngine()
    return _ENGINE_THREAD_LOCAL.engine
